### ISSUE TITLE
"Connected to Stream Deck Plugin"

### ISSUE THREAD

**Issue by bertoo87** [rmroc451/Flight-Tracker-StreamDeck#11]
Hi there.
this message pops up where the Hints for the game appear (upper part in the middle of the screen)
When it does this, i cannot controll anything anymorew, but i still get the readings from the Sim. I dont know what triggers this right now, trying to get my head around that. Pretty much everytime ive landed is what i remember, and i have to restart the Game completly.

**Comment by rmroc451** [comment]
This is a known issue that the original repo creator has been working on. We've talked about it, and he has some ideas. I'd check out https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/issues/24
