### ISSUE TITLE
Cannot install this  

### ISSUE THREAD

**Issue by chopperaddict** [rmroc451/Flight-Tracker-StreamDeck#23]
Below are some useful information that you can include to help with troubleshooting the issue:
- Stream Deck Plugin and MSFS version
- Description of the issue & expected behavior
- Steps to reproduce the issue
- If the issue happens consistently, an export of your profile would help tremendously.
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`
- Screenshots

I have downloaded this module to add to my Stream Deck system, but the file you tell me to Dbl/Click does not exist in my streamdeck folder system anywhere ?

There is not even a folder "Elgato" as mentioned above in my Appdata folder, despite having it working in basic form with FS2020 already ? and no files exist in my PC with the suffix "tech."

Please tell me what I need to do here ?

**Comment by rmroc451** [comment]
Hey @chopperaddict!

I'll have you move over to the [here ](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/releases)to grab releases. I make changes here and PR them into the upstream repo which gets released periodically.

Alternatively, Hy (the upstream repo's owner) has put the plugin in the stream deck plugin store as well!

I'm going to close this, and probably remove the releases on my repo so it doesn't confuse anyone. As well as update the forum post.
